[AppCheck] Fix unused isTokenAutoRefreshEnabled ivar warning
Stopped synthesizing a backing instance variable for the
isTokenAutoRefreshEnabled property in FIRAppCheckSettings because it is
unused, resulting in a warning when "-Wunused-property-ivar" is enabled.

This resolves the error "FIRAppCheckSettings.m:92:1: error: ivar
'_isTokenAutoRefreshEnabled' which backs the property is not referenced
in this property's accessor [-Werror,-Wunused-property-ivar]" when
building in google3 (where this warning is treated as an error).