Fix implicit conversions from ints to chars.
These conversions can alter the values, so the rodete compiler objects
with messages like:

  error: conversion to ‘char’ from ‘int’ may alter its value
  error: conversion to ‘char’ alters ‘int’ constant value

The second one in particular is slightly alarming, and results from
things like this:

  char c = 0xff;

However, this is contained within tests dealing with odd corner cases,
so I've just cast'd the problem away.  (i.e. static_cast<char>(0xff))