Get Windows and Linux builds to compile again (#4256)
* Rename IN to IN_ for compatibility with Windows

windows.h defines IN and INOUT macros that indicate the directionality
of parameters in the Windows API.

* Rename DeleteFile to DeleteSingleFile

This avoids a conflict with the Win32 macro, which expands to either
DeleteFileA or DeleteFileW, based on the Unicode mode of the build.

* Avoid using declarations of non-types outside classes

VS2017 doesn't accept these even though clang does.

* Avoid relying on default construction of type traits

This is a C++14 extension that VS2017 does not expose in C++11 mode.

* Add missing dependencies

* Define LevelDbPersistence::AppDataDirectory on Windows.

* Make Container a top-level type

This avoids a GCC error:

error: typedef ‘using value_type = int’ locally defined but not used [-Werror=unused-local-typedefs]

Removing value_type isn't actually possible because it is actually used,
but indirectly via template.