FSTTransactionTests: fix unused variable warning.
This fixes the following build error:

```
Firestore/Example/Tests/Integration/FSTTransactionTests.mm:541:30: error: variable 'snapshot' set but not used [-Werror,-Wunused-but-set-variable]
  FIRDocumentSnapshot *snapshot = [transaction getDocument:doc error:error];
```