Directly initialize `g_log_level` in `log_stdio.cc` to fix compilation errors.
In #7754, the `g_log_level` variable was changed from `LogLevel` to `std::atomic<LogLevel>` and it was left being initialized with the `=` operator; however, this caused some compilation errors, such as:

```
../Firestore/core/src/util/log_stdio.cc:30:37: error: use of deleted function ‘std::atomic<_Tp>::atomic(const std::atomic<_Tp>&) [with _Tp = firebase::firestore::util::LogLevel]’
30 | std::atomic<LogLevel> g_log_level = kLogLevelNotice;
   |                                     ^~~~~~~~~~~~~~~
```

The fix in this commit is to initialize `g_log_level` directly.