Make Container a top-level type
This avoids a GCC error:

error: typedef ‘using value_type = int’ locally defined but not used [-Werror=unused-local-typedefs]

Removing value_type isn't actually possible because it is actually used,
but indirectly via template.