Convert cmake build to (mostly) use urls rather than git clones
Exception: grpc. Due to it's use of git submodules, it's not completely
trivial to convert it (though probably wouldn't be too much more work.)

This helps address our build being throttled. (Maybe. This assumes
github allows more fetching of tgz's than clones.)