Revert "Firestore/core/test/unit/util/CMakeLists.txt: remove set(CMAKE_CXX_EXTENSIONS ON), which was added 7 years ago in https://github.com/firebase/firebase-ios-sdk/pull/715"
This reverts commit f0a3334845f9ca5bf8d10c86ca688375b3ba10ec.

The following compiler error results from removing `set(CMAKE_CXX_EXTENSIONS ON)`:

```
FAILED: Firestore/core/test/unit/util/CMakeFiles/firestore_util_test.dir/comparison_test.cc.o
/usr/bin/ccache /usr/bin/c++ -DCARES_STATICLIB -DFIREBASE_TESTS_BUILT_BY_CMAKE -DFIRESTORE_HAVE_CONFIG_DETECTED_H -DPB_ENABLE_MALLOC -DPB_FIELD_32BIT -DPB_NO_PACKED_STRUCTS=1 -Ifirebase-ios-sdk/main/build -Ifirebase-ios-sdk/main -Ifirebase-ios-sdk/main/build/external/src/abseil-cpp -Ifirebase-ios-sdk/main/Firestore/core/include -Ifirebase-ios-sdk/main/build/external/src/leveldb/include -Ifirebase-ios-sdk/main/build/external/src/snappy-build -Ifirebase-ios-sdk/main/build/external/src/snappy -Ifirebase-ios-sdk/main/build/external/src/nanopb -Ifirebase-ios-sdk/main/Firestore/Protos/nanopb -Ifirebase-ios-sdk/main/build/external/src/grpc/include -Ifirebase-ios-sdk/main/build/external/src/re2 -Ifirebase-ios-sdk/main/build/external/src/grpc-build/third_party/cares/cares -Ifirebase-ios-sdk/main/build/external/src/cares -Ifirebase-ios-sdk/main/build/external/src/protobuf/src -isystem firebase-ios-sdk/main/build/external/src/googletest/googletest/include -isystem firebase-ios-sdk/main/build/external/src/googletest/googletest -isystem firebase-ios-sdk/main/build/external/src/googletest/googlemock/include -isystem firebase-ios-sdk/main/build/external/src/googletest/googlemock -isystem $HOMEBREW_PREFIX/Cellar/openssl@3/3.4.1/include -Wno-format-zero-length -g -std=c++14 -Wall -Wextra -Werror -Wformat -Wuninitialized -fno-common -Wunused-function -Wunused-value -Wunused-variable -fdiagnostics-color -Wno-error=redundant-move -Wno-error=deprecated-declarations -Wreorder -Werror=reorder -MD -MT Firestore/core/test/unit/util/CMakeFiles/firestore_util_test.dir/comparison_test.cc.o -MF Firestore/core/test/unit/util/CMakeFiles/firestore_util_test.dir/comparison_test.cc.o.d -o Firestore/core/test/unit/util/CMakeFiles/firestore_util_test.dir/comparison_test.cc.o -c firebase-ios-sdk/main/Firestore/core/test/unit/util/comparison_test.cc
firebase-ios-sdk/main/Firestore/core/test/unit/util/comparison_test.cc:196:27: error: exponent has no digits
  196 |   double min_sub_normal = 0x1.0p-1074;
      |                           ^~~~~~
```